In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('sbert-align/data/clean_011223.csv')

/tmp/ipykernel_387/1552581445.py:1: DtypeWarning: Columns (38,65,66,118,119,122,123,146) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('sbert-align/data/clean_011223.csv')


In [3]:
df

ID                                         File  StartTime   EndTime  \
0      1099    20210720_173521EDT_PIN1099_VBM_DC-mrg.wav    212.126   212.748   
1      1099    20210720_173521EDT_PIN1099_VBM_DC-mrg.wav    356.816   358.287   
2      1099    20210720_173521EDT_PIN1099_VBM_DC-mrg.wav    357.992   365.806   
3      1099    20210720_173521EDT_PIN1099_VBM_DC-mrg.wav    378.516   380.540   
4      1099    20210720_173521EDT_PIN1099_VBM_DC-mrg.wav    204.762   205.497   
...     ...                                          ...        ...       ...   
37705  9946        20210630_142938EDT_PIN9946_VBM_SC.wav   1717.403  1725.753   
37706  9946        20210630_142938EDT_PIN9946_VBM_SC.wav   1701.391  1702.550   
37707  9946  20210721_143214EDT_PIN9946_VBM_DC-mplex.wav   1282.931  1291.740   
37708  9946  20210721_143214EDT_PIN9946_VBM_DC-mplex.wav   1280.147  1282.829   
37709  9946  20210721_143214EDT_PIN9946_VBM_DC-mplex.wav   1277.003  1281.273   

                                              Transcript Speaker  \
0                                                 Ready?   Adult   
1                             Even everything they have.   Child   
2      Oh my gosh. That sounds really good. um What k...   Adult   
3                     Okay. But what flavor would it be?   Adult   
4                                                   Mhm.   Child   
...                                                  ...     ...   
37705  Yeah. (()) um the front yeah like the one that...   Child   
37706                                           Oh okay.   Adult   
37707  I can go first. Okay. um. Take the biggest pal...   Adult   
37708                                       um. You can.   Child   
37709  Yeah. ((This is fun.)) Okay. Are you ready? Am...   Adult   

               Task    InterTurn      date  Latency  ...  Child  Parent  \
0         Questions  Adult2Child  20210720    6.629  ...      0       1   
1         Questions  Child2Adult  20210720    1.222  ...      1       0   
2         Questions  Adult2Child  20210720   -0.295  ...      0       1   
3         Questions  Adult2Child  20210720   -0.022  ...      0       1   
4         Questions  Child2Adult  20210720    0.266  ...      1       0   
...             ...          ...       ...      ...  ...    ...     ...   
37705  MatchingGame  Child2Adult  20210630   -1.636  ...      1       0   
37706  MatchingGame  Adult2Child  20210630      NaN  ...      0       1   
37707  MatchingGame  Adult2Child  20210721    0.102  ...      0       1   
37708  MatchingGame  Child2Adult  20210721   -1.126  ...      1       0   
37709  MatchingGame  Adult2Child  20210721   -0.427  ...      0       1   

       SelfChild2  SelfAdult2  Sex Familiarity     Self2     Self1    Other1  \
0        6.828127    6.828127  0.0  Unfamiliar  5.208540 -1.619587  0.070939   
1        1.600074    1.600074  0.0  Unfamiliar  0.834206 -0.765867       NaN   
2             NaN         NaN  0.0  Unfamiliar -0.393067       NaN  0.840897   
3        0.208682    0.208682  0.0  Unfamiliar -0.172206 -0.380888       NaN   
4       -0.028673   -0.028673  0.0  Unfamiliar  0.060790  0.089463 -1.619587   
...           ...         ...  ...         ...       ...       ...       ...   
37705   -1.643744   -1.643744  1.0    Familiar -1.200763  0.442981 -0.342903   
37706         NaN         NaN  1.0    Familiar       NaN       NaN -0.196950   
37707    0.396961    0.396961  1.0    Familiar -0.189836 -0.586797 -1.051784   
37708         NaN         NaN  1.0    Familiar -1.056921       NaN -0.563921   
37709         NaN         NaN  1.0    Familiar -0.563360       NaN       NaN   

       SelfChange  
0        6.828127  
1        1.600074  
2             NaN  
3        0.208682  
4       -0.028673  
...           ...  
37705   -1.643744  
37706         NaN  
37707    0.396961  
37708         NaN  
37709         NaN  

[37710 rows x 177 columns]

In [6]:
duplicates = df.groupby(['ID', 'Visit', 'Task', 'Turn']).count()

In [7]:
duplicates[duplicates['File']!=1]

File  StartTime  EndTime  Transcript  Speaker  \
ID   Visit Task      Turn                                                  
4869 1     Questions 2        2          2        2           2        2   
                     3        2          2        2           2        2   
                     4        2          2        2           2        2   
                     5        2          2        2           2        2   
                     6        2          2        2           2        2   
                     7        2          2        2           2        2   
                     8        2          2        2           2        2   
                     9        2          2        2           2        2   
                     10       2          2        2           2        2   
                     11       2          2        2           2        2   
                     12       2          2        2           2        2   
9611 1     Questions 2        2          2        2           2        2   
                     3        2          2        2           2        2   
                     4        2          2        2           2        2   
                     5        2          2        2           2        2   
                     6        2          2        2           2        2   
                     7        2          2        2           2        2   
                     8        2          2        2           2        2   
                     9        2          2        2           2        2   

                           InterTurn  date  Latency  PrevOtherLatency  \
ID   Visit Task      Turn                                               
4869 1     Questions 2             2     2        2                 0   
                     3             2     2        2                 2   
                     4             2     2        2                 2   
                     5             2     2        2                 2   
                     6             2     2        2                 2   
                     7             2     2        2                 2   
                     8             2     2        2                 2   
                     9             2     2        2                 2   
                     10            2     2        2                 2   
                     11            2     2        2                 2   
                     12            2     2        2                 2   
9611 1     Questions 2             2     2        2                 0   
                     3             2     2        2                 2   
                     4             2     2        2                 2   
                     5             2     2        2                 2   
                     6             2     2        2                 2   
                     7             2     2        2                 2   
                     8             2     2        2                 2   
                     9             2     2        2                 2   

                           PrevSelfLatency  ...  Child  Parent  SelfChild2  \
ID   Visit Task      Turn                   ...                              
4869 1     Questions 2                   0  ...      2       2           0   
                     3                   0  ...      2       2           0   
                     4                   2  ...      2       2           2   
                     5                   2  ...      2       2           2   
                     6                   2  ...      2       2           2   
                     7                   2  ...      2       2           2   
                     8                   2  ...      2       2           2   
                     9                   2  ...      2       2           2   
                     10                  2  ...      2       2           2   
                     11               

4869 and 9611 have repeated turns for Visit 1. Solution: remove the first of the two.

In [18]:
df[(df['ID']==9611) & (df['Visit']==1)].sort_values(by='Turn').head(n=50)[['Turn', 'Transcript', 'StartTime', 'EndTime', 'Speaker']]

Turn                                         Transcript  StartTime  \
33952     2                                      I flipped it.    154.292   
33960     2  Perfect thank you Madeline. *Alrighty so pleas...     44.330   
33953     3  Awesome okay my friend today we are planning a...    156.214   
33961     3            Addison, Anna, Daniella, Kara, Caitlyn,     51.470   
33954     4      uh One with lots of presents and (()) themed.    176.427   
33962     4                         Ooh very cool are those --     56.480   
33963     5                                       and Caitlyn,     57.124   
33955     5                 Oh what kind of theme would it be?    181.209   
33956     6                                              (()).    184.773   
33964     6                 (()) as -- are there two Caitlyns?     60.130   
33957     7  Oh very cool. So who do you think would come t...    186.640   
33965     7  There's one in my new school, and one in my ol...     63.980   
33958     8            Daniella, Kara, Caitlyn, Addison, Anna.    193.813   
33966     8  Oh that's so nice, so are they -- are all of t...     67.440   
33959     9  Hm very cool, so it sounds like you have a nic...    206.074   
33967     9                                            School.     74.326   
33968    10  Oh nice. *Alrighty, so uh we have all of our u...     75.882   
33969    11                                        um Playing?     86.476   
33970    12  Hm some some some things that I like to do at ...     90.820   
33971    13                                               (())    100.985   
33972    14  Please stop playing with the timer. Can you an...    103.287   
33973    15                                                 um    105.950   
33974    16              ((Do you want to hear the question))?    107.354   
33975    17                               Games that you play.    110.235   
33976    18                                               Mhm.    112.243   
33977    19                                  uh Candyland (())    113.314   
33978    20                            At your birthday party?    118.753   
33979    21                                                No.    120.165   
33980    22  {laugh} (()) Any types of games can be um -- t...    120.880   
33981    23                                               (())    136.530   
33982    24                       Can you answer her question?    137.055   
33983    25  uh Candyland is a board game where where four ...    138.301   
33984    26  Hm. Oh that sounds awesome a perfect game. So ...    149.882   
33985    27                                              Cake.    176.875   
33986    28                                                Mm.    178.250   
33987    29                                  Cookies and cake.    178.670   
33988    30                       Ooh I love this (()) so far.    181.029   
33989    31                                     ((Chocolate)).    182.110   
33990    32  Ooh chocolate. We have cake we have cookies. W...    183.840   
33991    33                                         Chocolate.    189.950   
33992    34  Okay chocolate cake. Are there going to be cho...    191.196   
33993    35           There are going to be chocolate cookies.    197.497   
33994    36  Oh my goodness I hear we have a sweet tooth. {...    199.630   
33995    37                          um (()) Lots of balloons.    222.448   
33996    38                                               Ooh.    231.650   
33997    39                     I would want lots of balloons.    231.858   
33998    40  Ooh that's fair okay. And then what type -- wh...    234.700   
33999    41                                 ((Blue)) and pink.    242.516   
34000    42  Hm blue and pink very nice. And then finally, ...    245.850   
34001    43                                               Yes.    259.420   

       EndTime Speaker  
33952  155.600   Child  
33960   49.610   Adult  
3395

In [26]:
df.sort_values(by=['ID', 'Visit', 'Task', 'Turn']).groupby(['ID', 'Visit', 'Task']).apply(lambda x: x[x['Speaker']==x.shift()['Speaker']][['ID', 'Visit', 'Task', 'Turn', 'Speaker', 'StartTime', 'EndTime', 'Transcript']])

ID  Visit          Task  Turn Speaker  \
ID   Visit Task                                                          
4869 1     Questions    17426  4869      1     Questions     2   Child   
                        17427  4869      1     Questions     3   Adult   
                        17428  4869      1     Questions     4   Child   
                        17429  4869      1     Questions     5   Adult   
                        17430  4869      1     Questions     6   Child   
                        17431  4869      1     Questions     7   Adult   
                        17304  4869      1     Questions     8   Child   
                        17305  4869      1     Questions     9   Adult   
                        17306  4869      1     Questions    10   Child   
                        17307  4869      1     Questions    11   Adult   
                        17425  4869      1     Questions    12   Child   
6985 7     MatchingGame 24267  6985      7  MatchingGame    94   Child   
9035 3     MatchingGame 28736  9035      3  MatchingGame   114   Adult   
                        28654  9035      3  MatchingGame   134   Child   
9043 1     MatchingGame 29005  9043      1  MatchingGame   176   Adult   
9611 1     Questions    33953  9611      1     Questions     3   Adult   
                        33954  9611      1     Questions     4   Child   
                        33955  9611      1     Questions     5   Adult   
                        33956  9611      1     Questions     6   Child   
                        33957  9611      1     Questions     7   Adult   
                        33958  9611      1     Questions     8   Child   
                        33959  9611      1     Questions     9   Adult   

                               StartTime   EndTime  \
ID   Visit Task                                      
4869 1     Questions    17426     32.552    33.501   
                        17427     34.336    40.340   
                        17428     41.462    44.002   
                        17429     45.330    49.210   
                        17430     50.040    58.736   
                        17431     57.164    57.894   
                        17304     59.012    59.528   
                        17305     59.131    69.700   
                        17306     72.600    74.933   
                        17307     75.679    82.134   
                        17425    164.822   165.623   
6985 7     MatchingGame 24267   1075.576  1084.590   
9035 3     MatchingGame 28736   1540.200  1543.581   
                        28654   1721.628  1751.648   
9043 1     MatchingGame 29005    907.883   908.296   
9611 1     Questions    33953    156.214   170.523   
                        33954    176.427   180.384   
                        33955    181.209   183.550   
                        33956    184.773   185.781   
                        33957    186.640   192.067   
                        33958    193.813   205.092   
                        33959    206.074   214.674   

                                                                      Transcript  
ID   Visit Task                                                                   
4869 1     Questions    17426                                      Yeah it does.  
                        17427  Awesome okay, so we have all of that taken car...  
                        17428                                   um The presents.  
                        17429  Ooh okay. um What type of presents should we h...  
                        17430  uh Clothes, money, or -- and like things in ge...  
                        17431                                                Hm.  
                        17304                                              Yeah.  
                        17305  Oh {laugh} okay cool, so hm we have our games ...  
                        17306                          um Wait what did you say?  
                        17307  Whose birthday 

In [ ]:
# 4869 and 9611 are taken care of

In [32]:
df[(df['ID']==9043) & (df['Visit']==1) & (df['Task']=='MatchingGame')].sort_values(by='Turn').iloc[20:50][['ID', 'Visit', 'Task', 'Turn', 'Speaker', 'StartTime', 'EndTime', 'Transcript']]
# Missing turns 172 to 175 for 9043 included

ID  Visit          Task  Turn Speaker  StartTime   EndTime  \
28941  9043      1  MatchingGame   170   Child    873.603   874.072   
29004  9043      1  MatchingGame   171   Adult    877.278   891.670   
29005  9043      1  MatchingGame   176   Adult    907.883   908.296   
29006  9043      1  MatchingGame   177   Child    908.908   914.892   
29007  9043      1  MatchingGame   178   Adult    916.194   920.400   
29008  9043      1  MatchingGame   179   Child    920.677   922.884   
29009  9043      1  MatchingGame   180   Adult    921.487   927.836   
29010  9043      1  MatchingGame   181   Child    929.989   935.021   
29011  9043      1  MatchingGame   182   Adult    931.941   933.703   
29012  9043      1  MatchingGame   183   Child    935.211   940.528   
28955  9043      1  MatchingGame   184   Adult    943.401   944.560   
28956  9043      1  MatchingGame   185   Child    946.420   948.452   
29013  9043      1  MatchingGame   186   Adult    948.721   951.991   
28958  9043      1  MatchingGame   187   Child    951.975   962.709   
28959  9043      1  MatchingGame   188   Adult    962.788   963.740   
28960  9043      1  MatchingGame   189   Child    964.899   966.249   
28896  9043      1  MatchingGame   190   Adult    966.614   967.043   
28897  9043      1  MatchingGame   191   Child    967.788   969.280   
28856  9043      1  MatchingGame   192   Adult    969.883   970.804   
28898  9043      1  MatchingGame   193   Child    972.268   975.386   
28899  9043      1  MatchingGame   194   Adult    975.393   987.561   
28900  9043      1  MatchingGame   195   Child    989.446   992.168   
28901  9043      1  MatchingGame   196   Adult    992.484   995.635   
28902  9043      1  MatchingGame   197   Child    996.126   998.237   
28903  9043      1  MatchingGame   198   Adult    998.124   999.656   
28904  9043      1  MatchingGame   199   Child    999.783  1001.013   
28905  9043      1  MatchingGame   200   Adult   1001.505  1010.419   
28906  9043      1  MatchingGame   201   Child   1011.493  1012.648   
28907  9043      1  MatchingGame   202   Adult   1012.660  1026.885   
28908  9043      1  MatchingGame   203   Child   1036.687  1040.743   

                                              Transcript  
28941                                              Okay.  
29004  Use your words as best as you can no peaking o...  
29005                                               Yes.  
29006  I think we put a snowflake directly on top of ...  
29007        Great and you see the snowman that's there?  
29008                    Mhm. Should we put a hat on it?  
29009  Can you -- I was going to say yeah please put ...  
29010  Orange and purple hat? Well that kind of goes ...  
29011                                               (())  
29012  oh oh oh oh oh you didn't say red, orange, and...  
28955                             On the snowman's head.  
28956                        Wouldn't his head melt off?  
29013   It is your turn. Tell me where to put something.  
28958  I say we put a snowball right next to the snow...  
28959                                      On what side?  
28960                                     The left side.  
28896                                              Okay.  
28897         ((Actually I just changed my mind)) right.  
28856                                              Okay.  
28898              Right side. Because I'm right handed.  
28899  Okay. Can we put a the large (()) can we put a...  
28900  Wait no they aren't all the same size, the lar...  
28901                           A Christmas tree um next  
28902                  No they aren't all the same size.  
28903                                        Okay. Okay.  
28904                       Wait they are the same size.  
28905  Okay we're going to put a Christmas tree to th...  
28906                               You said pair right?  
28907  Yes. So there's two Christmas trees on the lef...  
28908   uh ((this looks so weird)) lo

In [43]:
df[(df['ID']==6985) & (df['Visit']==7) & (df['Task']=='MatchingGame')].sort_values(by='Turn').iloc[30:70][['ID', 'Visit', 'Task', 'Turn', 'Speaker', 'StartTime', 'EndTime', 'Transcript']]
# Turn numbers jump from 44 to 94, everything else is missing

ID  Visit          Task  Turn Speaker  StartTime   EndTime  \
23853  6985      7  MatchingGame    32   Child    189.727   191.871   
23854  6985      7  MatchingGame    33   Adult    193.403   196.664   
23855  6985      7  MatchingGame    34   Child    196.874   197.643   
23856  6985      7  MatchingGame    35   Adult    201.599   202.165   
23857  6985      7  MatchingGame    36   Child    202.278   202.917   
23858  6985      7  MatchingGame    37   Adult    204.037   204.587   
23859  6985      7  MatchingGame    38   Child    204.684   207.127   
23860  6985      7  MatchingGame    39   Adult    207.742   208.195   
23861  6985      7  MatchingGame    40   Child    209.304   210.946   
23862  6985      7  MatchingGame    41   Adult    211.003   214.314   
23863  6985      7  MatchingGame    42   Child    214.791   216.028   
23864  6985      7  MatchingGame    43   Adult    215.617   217.639   
23865  6985      7  MatchingGame    44   Child    217.598   218.164   
24267  6985      7  MatchingGame    94   Child   1075.576  1084.590   
24268  6985      7  MatchingGame    95   Adult   1084.832  1086.976   
24256  6985      7  MatchingGame    96   Child   1090.245  1091.426   
24257  6985      7  MatchingGame    97   Adult   1092.196  1092.786   
24411  6985      7  MatchingGame    98   Child   1092.398  1096.783   
24412  6985      7  MatchingGame    99   Adult   1101.216  1121.049   
24413  6985      7  MatchingGame   100   Child   1124.075  1146.962   
24432  6985      7  MatchingGame   101   Adult   1147.059  1159.133   
24421  6985      7  MatchingGame   102   Child   1159.368  1159.991   
24422  6985      7  MatchingGame   103   Adult   1159.400  1173.295   
24277  6985      7  MatchingGame   104   Child   1175.694  1182.519   
24278  6985      7  MatchingGame   105   Adult   1181.685  1182.583   
24279  6985      7  MatchingGame   106   Child   1182.850  1183.627   
24280  6985      7  MatchingGame   107   Adult   1182.875  1185.132   
24024  6985      7  MatchingGame   108   Child   1185.881  1188.898   
24025  6985      7  MatchingGame   109   Adult   1186.884  1188.616   
24026  6985      7  MatchingGame   110   Child   1191.052  1214.013   
24027  6985      7  MatchingGame   111   Adult   1214.226  1214.768   
24028  6985      7  MatchingGame   112   Child   1214.824  1219.048   
24029  6985      7  MatchingGame   113   Adult   1219.654  1219.994   
24030  6985      7  MatchingGame   114   Child   1240.335  1241.646   
24031  6985      7  MatchingGame   115   Adult   1242.115  1242.592   
24032  6985      7  MatchingGame   116   Child   1249.698  1251.195   
24033  6985      7  MatchingGame   117   Adult   1250.507  1257.360   
24034  6985      7  MatchingGame   118   Child   1257.708  1259.577   
24035  6985      7  MatchingGame   119   Adult   1258.743  1264.443   
24036  6985      7  MatchingGame   120   Child   1263.060  1263.416   

                                              Transcript  
23853                                   I didn't mean t-  
23854    All right uh what do you think are we finished?  
23855                                              Yeah.  
23856                                              Okay.  
23857                                               Mom?  
23858                                              Yeah.  
23859                          How are you able to show?  
23860                                              Sure.  
23861                              I mean middle middle.  
23862  Oh, you didn't say middle until my sticker was...  
23863                                            Middle.  
23864                      ((it looks)) okay. All right.  
23865                                              (( ))  
24267  I see two pairs of sunglasses that are very ve...  
24268                                      Oh What else?  
24256                                         Sunscreen.  
24257                                                 Oh  
24411        Toy boat. W- Sail boat

In [45]:
df[(df['ID']==9035) & (df['Visit']==3) & (df['Task']=='MatchingGame')].sort_values(by='Turn')[['ID', 'Visit', 'Task', 'Turn', 'Speaker', 'StartTime', 'EndTime', 'Transcript']]
# jumping from 111 to 114 (then also jumping more)

ID  Visit          Task  Turn Speaker  StartTime   EndTime  \
28658  9035      3  MatchingGame   104   Child   1445.497  1452.973   
28659  9035      3  MatchingGame   105   Adult   1452.482  1455.997   
28660  9035      3  MatchingGame   106   Child   1456.988  1459.599   
28661  9035      3  MatchingGame   107   Adult   1460.250  1462.334   
28732  9035      3  MatchingGame   108   Child   1462.991  1487.784   
28733  9035      3  MatchingGame   109   Adult   1489.465  1494.979   
28734  9035      3  MatchingGame   110   Child   1505.089  1518.910   
28735  9035      3  MatchingGame   111   Adult   1525.205  1534.220   
28736  9035      3  MatchingGame   114   Adult   1540.200  1543.581   
28669  9035      3  MatchingGame   119   Child   1555.467  1558.626   
28671  9035      3  MatchingGame   124   Adult   1578.986  1584.555   
28672  9035      3  MatchingGame   125   Child   1584.633  1586.553   
28673  9035      3  MatchingGame   126   Adult   1586.587  1599.310   
28674  9035      3  MatchingGame   127   Child   1602.159  1628.592   
28675  9035      3  MatchingGame   128   Adult   1632.223  1639.927   
28676  9035      3  MatchingGame   129   Child   1641.746  1695.305   
28581  9035      3  MatchingGame   130   Adult   1700.492  1707.761   
28582  9035      3  MatchingGame   131   Child   1712.453  1713.982   
28654  9035      3  MatchingGame   134   Child   1721.628  1751.648   
28655  9035      3  MatchingGame   135   Adult   1750.497  1798.471   

                                              Transcript  
28658  And there's a stick with a marshmallow on it. ...  
28659          I know. Here, oh this is a fun one today.  
28660                                         {NSV} (())  
28661                        Okay. You want to go first?  
28732  Put the gr- the fish. The little, little fish ...  
28733        Cabin. In the middle, above the brown path.  
28734  Hm. ((Pick up the daylight three)) And put it ...  
28735  Put the -- Put the fire under the Christmas tree.  
28736                                                NaN  
28669                Put the boy with the marshmallow --  
28671       Put the little girl who's swimming above the  
28672                        I think there are like two.  
28673  Oh, there's two little girls swimming? Okay. P...  
28674  {NSV} ((This, no)) Put the latern fly, I don't...  
28675    Put the sun in the top left corner. In the sky.  
28676  {NSV} Where the um. Where the hole is? Put the...  
28581  Put the sleeping bag -- Put the red sleeping b...  
28582                                It's ((bob)) rocks.  
28654  Put the stick with the marshmallow -- Put the ...  
28655  And that is time on my timer. That's the five-...

In [46]:
df.sort_values(by=['ID', 'Visit', 'Task', 'Turn']).groupby(['ID', 'Visit', 'Task']).apply(lambda x: x[x['Turn']-x.shift()['Turn']>1][['ID', 'Visit', 'Task', 'Turn', 'Speaker', 'StartTime', 'EndTime', 'Transcript']])

ID  Visit          Task  Turn Speaker  \
ID   Visit Task                                                          
6985 7     MatchingGame 24267  6985      7  MatchingGame    94   Child   
9035 3     MatchingGame 28736  9035      3  MatchingGame   114   Adult   
                        28669  9035      3  MatchingGame   119   Child   
                        28671  9035      3  MatchingGame   124   Adult   
                        28654  9035      3  MatchingGame   134   Child   
     7     MatchingGame 28356  9035      7  MatchingGame    79   Child   
           Questions    28495  9035      7     Questions    22   Adult   
9043 1     MatchingGame 29005  9043      1  MatchingGame   176   Adult   

                               StartTime   EndTime  \
ID   Visit Task                                      
6985 7     MatchingGame 24267   1075.576  1084.590   
9035 3     MatchingGame 28736   1540.200  1543.581   
                        28669   1555.467  1558.626   
                        28671   1578.986  1584.555   
                        28654   1721.628  1751.648   
     7     MatchingGame 28356    829.136   829.597   
           Questions    28495    295.216   298.050   
9043 1     MatchingGame 29005    907.883   908.296   

                                                                      Transcript  
ID   Visit Task                                                                   
6985 7     MatchingGame 24267  I see two pairs of sunglasses that are very ve...  
9035 3     MatchingGame 28736                                                NaN  
                        28669                Put the boy with the marshmallow --  
                        28671       Put the little girl who's swimming above the  
                        28654  Put the stick with the marshmallow -- Put the ...  
     7     MatchingGame 28356                                                No.  
           Questions    28495         What else do you do on vacation in Hawaii?  
9043 1     MatchingGame 29005                                               Yes.

In [51]:
df[(df['ID']==9035) & (df['Visit']==1) & (df['Task']=='MatchingGame')].sort_values(by='Turn')[['ID', 'Visit', 'Task', 'Turn', 'Speaker', 'StartTime', 'EndTime', 'Transcript']]
# jumping from 111 to 114 (then also jumping more)

ID  Visit          Task  Turn Speaker  StartTime   EndTime  \
28459  9035      1  MatchingGame   162   Child   1906.498  1908.986   
28460  9035      1  MatchingGame   163   Adult   1909.556  1910.533   
28461  9035      1  MatchingGame   164   Child   1910.740  1912.368   
28462  9035      1  MatchingGame   165   Adult   1912.272  1913.291   
28463  9035      1  MatchingGame   166   Child   1913.255  1914.153   
...     ...    ...           ...   ...     ...        ...       ...   
28352  9035      1  MatchingGame   229   Adult   2517.840  2520.879   
28353  9035      1  MatchingGame   230   Child   2521.540  2523.360   
28334  9035      1  MatchingGame   231   Adult   2523.961  2542.097   
28335  9035      1  MatchingGame   232   Child   2546.745  2553.198   
28314  9035      1  MatchingGame   233   Adult   2552.125  2667.358   

                                              Transcript  
28459                          Are they actual stickers?  
28460                                          They are.  
28461                                (()) pick them off?  
28462                                      Well not yet.  
28463                                      I don't know.  
...                                                  ...  
28352  The Christmas tree that's all the way on the l...  
28353                             Is the elft this side?  
28334  um Let me give you a better direction then. Pu...  
28335                                   Put the um the--  
28314  Oh I don't mean to cut you off Talia, but that...  

[72 rows x 8 columns]

In [63]:
no_current = df.sort_values(by=['ID', 'Visit', 'Task', 'Turn']).groupby(['ID', 'Visit', 'Task'], as_index=False).apply(lambda x: x[x['Turn']-x.shift()['Turn']>1])[['ID', 'Visit', 'Task', 'Turn']].apply(lambda row: '_'.join(row.values.astype(str)), axis=1).values.tolist()

In [73]:
no_current, df['unique_id']

(['6985_7_MatchingGame_94',
  '9035_3_MatchingGame_114',
  '9035_3_MatchingGame_119',
  '9035_3_MatchingGame_124',
  '9035_3_MatchingGame_134',
  '9035_7_MatchingGame_79',
  '9035_7_Questions_22',
  '9043_1_MatchingGame_176'],
 0             1099_1_Questions_7
 1            1099_1_Questions_46
 2            1099_1_Questions_47
 3            1099_1_Questions_49
 4             1099_1_Questions_6
                   ...           
 37705    9946_4_MatchingGame_134
 37706    9946_4_MatchingGame_131
 37707    9946_7_MatchingGame_145
 37708    9946_7_MatchingGame_144
 37709    9946_7_MatchingGame_143
 Name: unique_id, Length: 37710, dtype: object)

In [65]:
df['unique_id'] = df[['ID', 'Visit', 'Task', 'Turn']].apply(lambda row: '_'.join(row.values.astype(str)), axis=1)

In [77]:
df['unique_id']

0             1099_1_Questions_7
1            1099_1_Questions_46
2            1099_1_Questions_47
3            1099_1_Questions_49
4             1099_1_Questions_6
                  ...           
37705    9946_4_MatchingGame_134
37706    9946_4_MatchingGame_131
37707    9946_7_MatchingGame_145
37708    9946_7_MatchingGame_144
37709    9946_7_MatchingGame_143
Name: unique_id, Length: 37710, dtype: object

In [82]:
df['no_previous'] = df['unique_id'].apply(lambda x: f"{'_'.join(x.split('_')[:3])}_{int(x.split('_')[-1])-1}" in no_current)

In [88]:
no_previous = df[df['no_previous']==True].unique_id.tolist()

In [ ]:
no_current # make both nan


In [92]:
import json 

exclude = {'alignment_current_to_1back': no_current, 'alignment_1back_to_2back': no_previous + no_current}
with open('sbert-align/data/exclude.json', 'w') as f:
    json.dump(exclude, f)

In [93]:
test = json.load(open('sbert-align/data/exclude.json'))

In [94]:
test

{'alignment_current_to_1back': ['6985_7_MatchingGame_94',
  '9035_3_MatchingGame_114',
  '9035_3_MatchingGame_119',
  '9035_3_MatchingGame_124',
  '9035_3_MatchingGame_134',
  '9035_7_MatchingGame_79',
  '9035_7_Questions_22',
  '9043_1_MatchingGame_176'],
 'alignment_1back_to_2back': ['6985_7_MatchingGame_95',
  '9035_7_MatchingGame_80',
  '9035_7_Questions_23',
  '9035_3_MatchingGame_135',
  '9035_3_MatchingGame_125',
  '9043_1_MatchingGame_177',
  '6985_7_MatchingGame_94',
  '9035_3_MatchingGame_114',
  '9035_3_MatchingGame_119',
  '9035_3_MatchingGame_124',
  '9035_3_MatchingGame_134',
  '9035_7_MatchingGame_79',
  '9035_7_Questions_22',
  '9043_1_MatchingGame_176']}